package com.jFinal.project.creation.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 * @author 凉雨时旧
 */
@SuppressWarnings("serial")
public abstract class BaseCoreJx3Member<M extends BaseCoreJx3Member<M>> extends Model<M> implements IBean {

	/**
	 * 会员表id
	 */
	public void setMemberId(java.lang.Integer memberId) {
		set("member_id", memberId);
	}
	
	/**
	 * 会员表id
	 */
	public java.lang.Integer getMemberId() {
		return getInt("member_id");
	}

	/**
	 * 会员账号
	 */
	public void setMemberNumber(java.lang.String memberNumber) {
		set("member_number", memberNumber);
	}
	
	/**
	 * 会员账号
	 */
	public java.lang.String getMemberNumber() {
		return getStr("member_number");
	}

	/**
	 * 会员名称
	 */
	public void setMemberName(java.lang.String memberName) {
		set("member_name", memberName);
	}
	
	/**
	 * 会员名称
	 */
	public java.lang.String getMemberName() {
		return getStr("member_name");
	}

	/**
	 * 会员头像
	 */
	public void setMemberAvatar(java.lang.String memberAvatar) {
		set("member_avatar", memberAvatar);
	}
	
	/**
	 * 会员头像
	 */
	public java.lang.String getMemberAvatar() {
		return getStr("member_avatar");
	}

	/**
	 * 会员性别
	 */
	public void setMemberSex(java.lang.String memberSex) {
		set("member_sex", memberSex);
	}
	
	/**
	 * 会员性别
	 */
	public java.lang.String getMemberSex() {
		return getStr("member_sex");
	}

	/**
	 * 会员生日
	 */
	public void setMemberBirthday(java.sql.Time memberBirthday) {
		set("member_birthday", memberBirthday);
	}
	
	/**
	 * 会员生日
	 */
	public java.sql.Time getMemberBirthday() {
		return get("member_birthday");
	}

	/**
	 * 会员邮箱
	 */
	public void setMemberMail(java.lang.String memberMail) {
		set("member_mail", memberMail);
	}
	
	/**
	 * 会员邮箱
	 */
	public java.lang.String getMemberMail() {
		return getStr("member_mail");
	}

	/**
	 * 会员手机号
	 */
	public void setMemberPhone(java.lang.String memberPhone) {
		set("member_phone", memberPhone);
	}
	
	/**
	 * 会员手机号
	 */
	public java.lang.String getMemberPhone() {
		return getStr("member_phone");
	}

	/**
	 * 会员居住地址
	 */
	public void setMemberAddress(java.lang.String memberAddress) {
		set("member_address", memberAddress);
	}
	
	/**
	 * 会员居住地址
	 */
	public java.lang.String getMemberAddress() {
		return getStr("member_address");
	}

	/**
	 * 会员游戏角色
	 */
	public void setMemberJx3Roles(java.lang.String memberJx3Roles) {
		set("member_jx3_roles", memberJx3Roles);
	}
	
	/**
	 * 会员游戏角色
	 */
	public java.lang.String getMemberJx3Roles() {
		return getStr("member_jx3_roles");
	}

	/**
	 * 会员个性签名
	 */
	public void setMemberSignature(java.lang.String memberSignature) {
		set("member_signature", memberSignature);
	}
	
	/**
	 * 会员个性签名
	 */
	public java.lang.String getMemberSignature() {
		return getStr("member_signature");
	}

	/**
	 * 创建人id
	 */
	public void setCreateId(java.lang.Integer createId) {
		set("create_id", createId);
	}
	
	/**
	 * 创建人id
	 */
	public java.lang.Integer getCreateId() {
		return getInt("create_id");
	}

	/**
	 * 创建时间
	 */
	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	/**
	 * 更新人id
	 */
	public void setUpdateId(java.lang.Integer updateId) {
		set("update_id", updateId);
	}
	
	/**
	 * 更新人id
	 */
	public java.lang.Integer getUpdateId() {
		return getInt("update_id");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

}
