package com.jFinal.project.creation.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTblWhiteList8479<M extends BaseTblWhiteList8479<M>> extends Model<M> implements IBean {

	/**
	 * 表主键
	 */
	public void setListId(java.lang.Integer listId) {
		set("list_id", listId);
	}
	
	/**
	 * 表主键
	 */
	public java.lang.Integer getListId() {
		return getInt("list_id");
	}

	/**
	 * 银行号
	 */
	public void setInstCd(java.lang.String instCd) {
		set("inst_cd", instCd);
	}
	
	/**
	 * 银行号
	 */
	public java.lang.String getInstCd() {
		return getStr("inst_cd");
	}

	/**
	 * 证件号码
	 */
	public void setDocNu(java.lang.String docNu) {
		set("doc_nu", docNu);
	}
	
	/**
	 * 证件号码
	 */
	public java.lang.String getDocNu() {
		return getStr("doc_nu");
	}

	/**
	 * 手机号
	 */
	public void setPhoneNu(java.lang.String phoneNu) {
		set("phone_nu", phoneNu);
	}
	
	/**
	 * 手机号
	 */
	public java.lang.String getPhoneNu() {
		return getStr("phone_nu");
	}

	/**
	 * 银行白名单用户姓名
	 */
	public void setBankUserNa(java.lang.String bankUserNa) {
		set("bank_user_na", bankUserNa);
	}
	
	/**
	 * 银行白名单用户姓名
	 */
	public java.lang.String getBankUserNa() {
		return getStr("bank_user_na");
	}

}
