package com.jFinal.project.creation.common.model;

import com.jFinal.project.creation.common.model.base.BaseCoreJx3Member;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CoreJx3Member extends BaseCoreJx3Member<CoreJx3Member> {
	public static final CoreJx3Member dao = new CoreJx3Member().dao();
}
