package com.jFinal.project.creation.common.model;

import com.jFinal.project.creation.common.model.base.BaseTblWhiteList8479;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TblWhiteList8479 extends BaseTblWhiteList8479<TblWhiteList8479> {
	public static final TblWhiteList8479 dao = new TblWhiteList8479().dao();
}
